apiVersion: apps/v1
kind: Deployment
metadata:
  name: muzic-server-deployment
  namespace: mzsv
  labels:
    app: muzic-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: muzic-server
  template:
    metadata:
      labels:
        app: muzic-server
    spec:
      containers:
        - name: muzic-server
          image: hienvinh/mz-sv:0.0.2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: postgres-service
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: muzicdb
            - name: DB_USER
              value: postgres
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: muzic-server-service
  namespace: mzsv
spec:
  selector:
    app: muzic-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30080
  type: NodePort
