apiVersion: apps/v1
kind: Deployment
metadata:
  name: muzic-client
  labels:
    app: muzic-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: muzic-client
  template:
    metadata:
      labels:
        app: muzic-client
    spec:
      containers:
        - name: muzic-client
          image: hienvinh/mz-cli:0.0.1
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 2
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: muzic-client
  labels:
    app: muzic-client
spec:
  type: NodePort
  selector:
    app: muzic-client
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30081
